Added Traditional Chinese (zh_tw.json)
Razuuu/advanced-hud-fabric pull request #3
Opened 2024-07-03 16:29 UTC by yichifauzi

Added Traditional Chinese translations

2024-07-05 12:06 UTC, notlin4 requested changes

2024-07-05 12:06 UTC, notlin4 commented on src/main/resources/assets/advancedhud/lang/zh_tw.json
> +  "text.autoconfig.advancedhud.option.holdKeyToShowFps": "「按鍵顯示 HUD」 模式",
```suggestion
  "text.autoconfig.advancedhud.option.holdKeyToShowFps": "「按住按鍵顯示 HUD」模式",
```

2024-07-05 12:06 UTC, notlin4 commented on src/main/resources/assets/advancedhud/lang/zh_tw.json
> +  "key.advancedhud.toggleFpsOverlay": "切換 HUD 疊加層",
```suggestion
  "key.advancedhud.toggleFpsOverlay": "切換 HUD 覆蓋層",
```

2024-07-05 12:06 UTC, notlin4 commented on src/main/resources/assets/advancedhud/lang/zh_tw.json
> +  "text.autoconfig.advancedhud.option.enableCooperativesHud": "顯示 座標",
```suggestion
  "text.autoconfig.advancedhud.option.enableCooperativesHud": "顯示座標",
```

2024-07-05 12:06 UTC, notlin4 commented on src/main/resources/assets/advancedhud/lang/zh_tw.json
> +  "text.autoconfig.advancedhud.option.enabled": "啟用",
```suggestion
  "text.autoconfig.advancedhud.option.enabled": "已啟用",
```

2024-07-08 21:51 UTC, Razuuu commented
What's about [this](https://github.com/Razuuu/advanced-hud-fabric/pull/3/files/8d1e409b328e94816e3d13303a62f09b1451f1f9)?

2024-07-09 10:04 UTC, yichifauzi commented
> What's about [this](https://github.com/Razuuu/advanced-hud-fabric/pull/3/files/8d1e409b328e94816e3d13303a62f09b1451f1f9)?

i think it's ready to merged

2024-07-09 16:08 UTC, notlin4 approved these changes

2024-07-09 19:37 UTC, Razuuu commented
Cherry picked it, commit is [5389a33](https://github.com/Razuuu/advanced-hud-fabric/commit/5389a33eab525a8d77461e82cd1b33e881dfeff1).

2024-07-09 19:37 UTC, closed without merging